name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: docker:20.10.8
    steps:
    - uses: docker/login-action@v1
    - name: Login to Docker Hub
      with:
        registry: <registry-name>.azurecr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


