name: Docker Image CI

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v2
      - run: docker build . --file app.Dockerfile --tag my-image-name:$(date +%s)
      - run: docker pull ${{ secrets.DOCKER_REGISTRY }}/ci_cd_test:hot || true
