name: Docker Image CI

on:
  push:
    branches: main

jobs:
  login:
    runs-on: docker:20.10.8
    steps:
      -
        name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v2
      - run: docker pull ${{ secrets.DOCKER_REGISTRY }}/app:hot || true
      - run: docker-compose build
      - run: docker tag app:latest ${{ secrets.DOCKER_REGISTRY }}/app:latest
      - run: docker tag app:latest ${{ secrets.DOCKER_REGISTRY }}/app:hot
      - run: docker images
      - run: docker push ${{ secrets.DOCKER_REGISTRY }}/app:latest
      - run: docker push ${{ secrets.DOCKER_REGISTRY }}/app:hot
