name: Docker Image CI

on:
  push:
#    branches: main
    tags:
      - v*

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v2
      - run: docker pull ${{ secrets.DOCKER_REGISTRY }}/app:hot || true
      - run: docker-compose build
      - run: docker tag app:latest ${{ secrets.DOCKER_REGISTRY }}/app:${{ github.event.release.tag_name }}
      - run: docker tag app:latest ${{ secrets.DOCKER_REGISTRY }}/app:hot
      - run: docker images
      - run: docker push ${{ secrets.DOCKER_REGISTRY }}/app:${{ github.event.release.tag_name }}
      - run: docker push ${{ secrets.DOCKER_REGISTRY }}/app:hot
